modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/kihira/PlayerRugs/issues"
license="MIT"

[[mods]]
modId="playerrugs"
version="${file.jarVersion}"
displayName="Player Rugs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/player-rugs"
authors="Kihira, Mrbysco"
description='''
Everyone in #kihira on esper.net
'''